# Inicializar la variable

In [1]:
i=4

# Elevar a un exponente

In [2]:
i**4

256

# Multiplicación almacenada en la misma variable

In [3]:
i*=10 # equivalente a i=i*10

In [4]:
i

40

# División almacenada en la misma variable

In [5]:
i/=10

In [6]:
i

4.0

# Sustracción almacenada en la misma variable

In [7]:
i-=1

In [8]:
i

3.0

# Adición almacenada en la misma variable

In [9]:
i+=10

In [10]:
i

13.0

# División entera almacenada en la misma variable

In [11]:
i //=3

In [12]:
i

4.0

# Residuo almecenado en la misma variable

In [13]:
i%=3

In [14]:
i

1.0

# Iteraciones manuales

In [15]:
contador=1

In [16]:
contador+=1
contador

2

In [17]:
contador+=1
contador

3

In [18]:
contador+=1
contador

4

## Strings

Comparación de cadenas

In [1]:
cadena1,cadena2='Hola','Mundo'
cadena1==cadena2

False

Comparación de listas

In [2]:
lista1,lista2=[3,'Gato','Sofia'],[5,'Perro']
lista1==lista2

False

Extracción de letras

In [3]:
b='Murcielago'

In [4]:
b[0]

'M'

In [5]:
b[::-1]

'ogaleicruM'

In [6]:
b[4:8]

'iela'

In [7]:
b[4:8]==b

False

In [8]:
b[4:8]!=b

True

# Máscaras

Importar Numpy

In [9]:
import numpy as np

Crear matriz

In [15]:
a=np.arange(1,8)
a

array([1, 2, 3, 4, 5, 6, 7])

Definir máscara

In [16]:
mascara=a>3
mascara

array([False, False, False,  True,  True,  True,  True])

Filtrar

In [19]:
filtrado=np.array(list(filter(lambda x:x>3,a)))
filtrado

array([4, 5, 6, 7])