Matriz entre el rango 3 a mi edad (22)

In [4]:
# importar libreria
import numpy as np

# crear matriz
matriz=np.arange(3,23)

# mostrar matriz
matriz

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22])

Crear un arreglo con los siguientes elementos: [0,1,2,3,4,0,1,2,3,4]

In [2]:
matriz_2=np.array([0,1,2,3,4,0,1,2,3,4])
matriz_2

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

Ordenar arreglo en forma ascendente

In [3]:
matriz_2.sort()
matriz_2

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])